services:
  - type: web
    name: my-scraper-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true